soc: oppo_devinfo: Fix incorrect string comparison
 * i literally forgot the fact that this is C and not C++, lmfao
 * somehow this ended up working fine tho

../drivers/soc/oppo/oppo_devinfo/device_info.c:200:11: error: result of comparison against a string literal is unspecified (use an explicit string comparison function instead) [-Werror,-Wstring-compare]
        if (name == "lcd") {
                 ^  ~~~~~
1 error generated.